import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/themes';

export const foodDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.lightGrey,
  },
  headerWrapper: {
    backgroundColor: COLORS.white,
    paddingHorizontal: 20,
    paddingTop: 0,
    paddingBottom: 12,
    borderBottomWidth: 0,
    marginTop: -20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  headerButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  headerButtonPlaceholder: {
    width: 44,
    height: 44,
  },
  headerTitleGroup: {
    flex: 1,
  },
  eyebrowLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.grey,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 2,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: COLORS.darkGrey,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 48,
  },
  imageContainer: {
    width: '100%',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 32,
    backgroundColor: 'transparent',
    alignItems: 'center',
    position: 'relative',
  },
  imageBackdrop: {
    position: 'absolute',
    top: 24,
    left: 48,
    right: 48,
    bottom: 12,
    backgroundColor: COLORS.white,
    borderRadius: 36,
    opacity: 0.6,
    zIndex: 0,
  },
  imageCard: {
    width: '100%',
    maxWidth: 440,
    aspectRatio: 4 / 3,
    backgroundColor: COLORS.background,
    borderRadius: 36,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 14,
    zIndex: 1,
  },
  dishImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  imagePlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.lightGrey,
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 56,
    gap: 20,
  },
  heroTitleCard: {
    marginTop: 0,
    backgroundColor: COLORS.background,
    padding: 20,
    borderRadius: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 6,
  },
  metaChip: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: COLORS.lightGrey,
  },
  metaChipText: {
    fontSize: 14,
    color: COLORS.darkGrey,
    fontWeight: '500',
  },
  title: {
    fontSize: 26,
    fontWeight: 'bold',
    color: COLORS.darkGrey,
    marginTop: 4,
  },
  heroSummary: {
    marginTop: 12,
    fontSize: 15,
    color: COLORS.grey,
    lineHeight: 22,
  },
  heroStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  heroStatCard: {
    flex: 1,
    minWidth: 110,
    backgroundColor: COLORS.background,
    borderRadius: 20,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 4,
  },
  heroStatIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: COLORS.lightGrey,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  heroStatLabel: {
    fontSize: 13,
    color: COLORS.grey,
    marginBottom: 4,
  },
  heroStatValue: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.darkGrey,
  },
  sectionStack: {
    gap: 16,
  },
  sectionCard: {
    padding: 20,
    borderRadius: 24,
    backgroundColor: COLORS.background,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    elevation: 5,
  },
  sectionCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sectionCardTitleGroup: {
    flex: 1,
  },
  sectionCardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.darkGrey,
  },
  sectionCardSubtitle: {
    marginTop: 4,
    fontSize: 14,
    color: COLORS.grey,
  },
  sectionCardIcon: {
    width: 40,
    height: 40,
    borderRadius: 16,
    backgroundColor: COLORS.lightGrey,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionDivider: {
    height: 1,
    backgroundColor: 'rgba(0,0,0,0.08)',
    marginVertical: 16,
  },
  dateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  dateText: {
    fontSize: 14,
    color: COLORS.grey,
    marginLeft: 8,
  },
  descriptionSection: {
    marginBottom: 12,
  },
  descriptionText: {
    fontSize: 16,
    color: COLORS.grey,
    lineHeight: 24,
    marginBottom: 12,
  },
  listContainer: {
    gap: 12,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  listItemIcon: {
    width: 32,
    height: 32,
    borderRadius: 12,
    backgroundColor: COLORS.lightGrey,
    justifyContent: 'center',
    alignItems: 'center',
  },
  listItemText: {
    flex: 1,
    fontSize: 16,
    color: COLORS.darkGrey,
    lineHeight: 20,
  },
  recipeContainer: {
    marginTop: 24,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    gap: 12,
  },
  recipeError: {
    marginTop: 12,
    fontSize: 14,
    color: COLORS.purple,
  },
  stepsContainer: {
    marginTop: 12,
    gap: 14,
  },
  stepCard: {
    padding: 18,
    borderRadius: 20,
    backgroundColor: COLORS.lightGrey,
    gap: 10,
  },
  stepBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: COLORS.background,
  },
  stepBadgeText: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.darkGrey,
  },
  stepDescription: {
    fontSize: 15,
    color: COLORS.darkGrey,
    lineHeight: 18,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: COLORS.grey,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    marginTop: 16,
    fontSize: 18,
    color: COLORS.darkGrey,
    textAlign: 'center',
    marginBottom: 24,
  },
  backButtonText: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: COLORS.purple,
    borderRadius: 20,
  },
  backButtonTextLabel: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  reviewsContainer: {
    marginTop: 24,
  },
  statsContainer: {
    marginTop: 12,
    marginBottom: 16,
    padding: 16,
    borderRadius: 16,
    backgroundColor: COLORS.lightGrey,
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  statsItem: {
    alignItems: 'center',
    flex: 1,
  },
  statsValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.darkGrey,
    marginBottom: 8,
  },
  statsLabel: {
    fontSize: 14,
    color: COLORS.grey,
  },
  statsStars: {
    marginTop: 4,
  },
  statsDivider: {
    width: 1,
    height: 40,
    backgroundColor: COLORS.grey,
    opacity: 0.3,
  },
  addReviewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: COLORS.lightGrey,
    marginTop: 12,
    marginBottom: 16,
    gap: 8,
  },
  addReviewButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.purple,
  },
  reviewForm: {
    marginTop: 12,
    marginBottom: 16,
    padding: 16,
    borderRadius: 16,
    backgroundColor: COLORS.lightGrey,
  },
  formLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.darkGrey,
    marginBottom: 12,
  },
  ratingSelector: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 16,
  },
  commentInput: {
    borderWidth: 1,
    borderColor: COLORS.grey,
    borderRadius: 12,
    padding: 12,
    fontSize: 15,
    color: COLORS.darkGrey,
    backgroundColor: COLORS.white,
    minHeight: 100,
    marginBottom: 12,
  },
  submitButton: {
    flex: 1,
    backgroundColor: COLORS.purple,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  reviewsList: {
    marginTop: 12,
    gap: 12,
  },
  reviewCard: {
    padding: 16,
    borderRadius: 16,
    backgroundColor: COLORS.lightGrey,
  },
  reviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  reviewUserInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 12,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  avatarPlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.grey,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  reviewUserDetails: {
    flex: 1,
  },
  reviewUserName: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.darkGrey,
    marginBottom: 4,
  },
  reviewDate: {
    fontSize: 12,
    color: COLORS.grey,
  },
  reviewComment: {
    fontSize: 15,
    color: COLORS.darkGrey,
    lineHeight: 18,
  },
  emptyReviewsText: {
    marginTop: 12,
    fontSize: 14,
    color: COLORS.grey,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  userReviewCard: {
    backgroundColor: '#F0E6FF',
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: COLORS.purple,
  },
  userReviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  userReviewTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.purple,
  },
  userReviewActions: {
    flexDirection: 'row',
    gap: 8,
  },
  iconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ratingDisplay: {
    flexDirection: 'row',
    gap: 4,
    marginBottom: 12,
  },
  userReviewComment: {
    fontSize: 15,
    color: COLORS.darkGrey,
    lineHeight: 22,
  },
  reviewFormActions: {
    flexDirection: 'row',
    gap: 12,
  },
  deleteButton: {
    flex: 1,
    backgroundColor: '#FFE5E5',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    borderWidth: 1,
    borderColor: '#FF3B30',
  },
  deleteButtonText: {
    color: '#FF3B30',
    fontSize: 16,
    fontWeight: '600',
  },
});

