import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/themes';

export const foodDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 12,
    paddingHorizontal: 20,
    paddingBottom: 12,
    backgroundColor: COLORS.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 6,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.lightGrey,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.darkGrey,
  },
  headerSpacer: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 32,
  },
  imageContainer: {
    width: '100%',
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 32,
    backgroundColor: COLORS.white,
    alignItems: 'center',
  },
  imageCard: {
    width: '100%',
    aspectRatio: 1,
    maxWidth: 360,
    backgroundColor: COLORS.lightGrey,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 20,
  },
  dishImage: {
    width: '85%',
    height: '85%',
  },
  imagePlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  content: {
    padding: 20,
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: -24,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.darkGrey,
    marginBottom: 12,
  },
  dateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  dateText: {
    fontSize: 14,
    color: COLORS.grey,
    marginLeft: 8,
  },
  descriptionContainer: {
    marginTop: 8,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.darkGrey,
    marginBottom: 16,
  },
  descriptionSection: {
    marginBottom: 16,
  },
  descriptionText: {
    fontSize: 16,
    color: COLORS.darkGrey,
    lineHeight: 20,
    marginBottom: 8,
  },
  listContainer: {
    marginLeft: 8,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  bulletPoint: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.purple,
    marginTop: 8,
    marginRight: 12,
  },
  listItemText: {
    flex: 1,
    fontSize: 16,
    color: COLORS.darkGrey,
    lineHeight: 20,
  },
  recipeContainer: {
    marginTop: 24,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    gap: 12,
  },
  recipeError: {
    marginTop: 12,
    fontSize: 14,
    color: COLORS.purple,
  },
  stepsContainer: {
    marginTop: 12,
    gap: 12,
  },
  stepCard: {
    padding: 16,
    borderRadius: 16,
    backgroundColor: COLORS.lightGrey,
  },
  stepNumber: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.darkGrey,
    marginBottom: 8,
  },
  stepDescription: {
    fontSize: 15,
    color: COLORS.darkGrey,
    lineHeight: 18,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: COLORS.grey,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    marginTop: 16,
    fontSize: 18,
    color: COLORS.darkGrey,
    textAlign: 'center',
    marginBottom: 24,
  },
  backButtonText: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: COLORS.purple,
    borderRadius: 20,
  },
  backButtonTextLabel: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  reviewsContainer: {
    marginTop: 24,
  },
  statsContainer: {
    marginTop: 12,
    marginBottom: 16,
    padding: 16,
    borderRadius: 16,
    backgroundColor: COLORS.lightGrey,
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  statsItem: {
    alignItems: 'center',
    flex: 1,
  },
  statsValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.darkGrey,
    marginBottom: 8,
  },
  statsLabel: {
    fontSize: 14,
    color: COLORS.grey,
  },
  statsStars: {
    marginTop: 4,
  },
  statsDivider: {
    width: 1,
    height: 40,
    backgroundColor: COLORS.grey,
    opacity: 0.3,
  },
  addReviewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: COLORS.lightGrey,
    marginTop: 12,
    marginBottom: 16,
    gap: 8,
  },
  addReviewButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.purple,
  },
  reviewForm: {
    marginTop: 12,
    marginBottom: 16,
    padding: 16,
    borderRadius: 16,
    backgroundColor: COLORS.lightGrey,
  },
  formLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.darkGrey,
    marginBottom: 12,
  },
  ratingSelector: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 16,
  },
  commentInput: {
    borderWidth: 1,
    borderColor: COLORS.grey,
    borderRadius: 12,
    padding: 12,
    fontSize: 15,
    color: COLORS.darkGrey,
    backgroundColor: COLORS.white,
    minHeight: 100,
    marginBottom: 12,
  },
  submitButton: {
    backgroundColor: COLORS.purple,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  reviewsList: {
    marginTop: 12,
    gap: 12,
  },
  reviewCard: {
    padding: 16,
    borderRadius: 16,
    backgroundColor: COLORS.lightGrey,
  },
  reviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  reviewUserInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 12,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  avatarPlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.grey,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  reviewUserDetails: {
    flex: 1,
  },
  reviewUserName: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.darkGrey,
    marginBottom: 4,
  },
  reviewDate: {
    fontSize: 12,
    color: COLORS.grey,
  },
  reviewComment: {
    fontSize: 15,
    color: COLORS.darkGrey,
    lineHeight: 18,
  },
  emptyReviewsText: {
    marginTop: 12,
    fontSize: 14,
    color: COLORS.grey,
    textAlign: 'center',
    fontStyle: 'italic',
  },
});

