import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/themes';

export const groupStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: COLORS.white,
  },
  headerIcon: {
    padding: 4,
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.darkGrey,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 100, // Space for FAB
    gap: 16,
    backgroundColor: COLORS.background,
  },
  familyCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 3,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 4,
  },
  familyAvatarContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: COLORS.orange,
    overflow: 'hidden',
    backgroundColor: COLORS.white,
  },
  familyAvatar: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  familyAvatarPlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.lightBlue,
  },
  familyInfo: {
    flex: 1,
    gap: 4,
  },
  familyName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.darkGrey,
    marginBottom: 4,
  },
  familyDetails: {
    fontSize: 14,
    color: COLORS.darkGrey,
    marginBottom: 2,
  },
  familyMembers: {
    fontSize: 14,
    color: COLORS.grey,
  },
  menuButton: {
    padding: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.secondary, // Green color for FAB
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  emptyState: {
    paddingVertical: 80,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  emptyStateText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.darkGrey,
    textAlign: 'center',
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: COLORS.grey,
    textAlign: 'center',
    paddingHorizontal: 40,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  loadingText: {
    fontSize: 16,
    color: COLORS.grey,
  },
  errorContainer: {
    paddingVertical: 80,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  errorText: {
    fontSize: 16,
    color: COLORS.grey,
    textAlign: 'center',
    paddingHorizontal: 32,
  },
  retryButton: {
    backgroundColor: COLORS.purple,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    marginTop: 8,
  },
  retryButtonText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '600',
  },
  // Tab Styles
  tabContainer: {
    flexDirection: 'row',
    paddingHorizontal: 10,
    paddingVertical: 12,
    paddingBottom: 0,
    backgroundColor: COLORS.white,
    // justifyContent: 'space-evenly', // Removed to allow scrolling
    borderBottomWidth: 1,
    borderBottomColor: COLORS.lightGrey,
  },
  tab: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabActive: {
    borderBottomColor: COLORS.purple,
  },
  tabText: {
    fontSize: 15,
    fontWeight: '500',
    color: COLORS.darkGrey,
    opacity: 0.6,
  },
  tabTextActive: {
    color: COLORS.purple,
    opacity: 1,
    fontWeight: '600',
  },
  // Member count
  memberCountContainer: {
    paddingVertical: 8,
  },
  memberCountText: {
    fontSize: 14,
    color: COLORS.darkGrey,
    fontWeight: '500',
  },
  // Search bar
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.backgroundLight,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 16,
    gap: 8,
  },
  searchIcon: {
    marginRight: 4,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: COLORS.darkGrey,
    padding: 0,
  },
  // Members List Styles
  membersList: {
    gap: 12,
    paddingBottom: 20,
  },
  memberCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 3,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  memberAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    overflow: 'hidden',
  },
  memberAvatarImage: {
    width: '100%',
    height: '100%',
  },
  memberAvatarPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: COLORS.purple,
    justifyContent: 'center',
    alignItems: 'center',
  },
  memberAvatarText: {
    fontSize: 20,
    fontWeight: '600',
    color: COLORS.white,
  },
  memberInfo: {
    flex: 1,
    gap: 4,
  },
  memberName: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.darkGrey,
  },
  memberEmail: {
    fontSize: 13,
    color: COLORS.grey,
  },
  roleBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  roleBadgeOwner: {
    backgroundColor: '#E3F2FD',
  },
  roleBadgeManager: {
    backgroundColor: '#FFF3E0',
  },
  roleBadgeMember: {
    backgroundColor: '#E8F5E9',
  },
  roleText: {
    fontSize: 12,
    fontWeight: '600',
  },
  roleTextOwner: {
    color: '#1976D2',
  },
  roleTextManager: {
    color: '#F57C00',
  },
  roleTextMember: {
    color: '#2E7D32',
  },
  // Shopping List Styles
  dateCarouselContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 0,
    paddingVertical: 16,
    backgroundColor: COLORS.white,
    gap: 6,
    overflow: 'hidden',
    width: '100%',
  },
  dateNavButton: {
    width: 36,
    height: 36,
    padding: 6,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
    flexGrow: 0,
    overflow: 'hidden',
  },
  dateCarousel: {
    flexDirection: 'row',
    gap: 6,
    flex: 1,
    width: '100%',
  },
  dateItem: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 12,
    backgroundColor: COLORS.lightGrey,
  },
  dateItemActive: {
    backgroundColor: COLORS.purple,
  },
  dateWeekday: {
    fontSize: 12,
    color: COLORS.darkGrey,
    opacity: 0.7,
  },
  dateWeekdayActive: {
    color: COLORS.white,
    opacity: 1,
  },
  dateDay: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.darkGrey,
    marginTop: 4,
  },
  dateDayActive: {
    color: COLORS.white,
  },
  shoppingListsContainer: {
    gap: 16,
  },
  shoppingListCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    width: '90%',
    alignSelf: 'center',
    marginTop: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    gap: 12,
  },
  shoppingListHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.lightGrey,
  },
  shoppingListTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.primary,
  },
  shoppingListCost: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.purple,
  },
  shoppingItemsContainer: {
    gap: 10,
  },
  shoppingItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 8,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: COLORS.grey,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: COLORS.purple,
    borderColor: COLORS.purple,
  },
  itemImage: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: COLORS.backgroundLight,
  },
  itemInfo: {
    flex: 1,
    gap: 4,
  },
  itemName: {
    fontSize: 15,
    fontWeight: '500',
    color: COLORS.darkGrey,
  },
  itemNameChecked: {
    textDecorationLine: 'line-through',
    color: COLORS.grey,
  },
  itemDetails: {
    fontSize: 13,
    color: COLORS.grey,
  },
  itemQuantity: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.darkGrey,
  },
  addItemButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.purple,
    borderStyle: 'dashed',
    marginTop: 4,
  },
  addItemButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.purple,
  },
  deleteListButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.red,
    borderStyle: 'dashed',
    marginTop: 4,
  },
  deleteListButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.red,
  },
  warningContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 12,
    backgroundColor: '#FFF4E5',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FFB74D',
    marginTop: 8,
  },
  warningText: {
    flex: 1,
    fontSize: 13,
    color: '#E65100',
    lineHeight: 18,
  },
  fabButton: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.purple,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 24,
    width: '90%',
    maxWidth: 400,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 10,
    flexDirection: 'column',
    maxHeight: '85%',
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.darkGrey,
  },
  modalCloseButton: {
    padding: 4,
  },
  modalBody: {
    gap: 16,
  },
  modalLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.darkGrey,
    marginBottom: 8,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: COLORS.lightGrey,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 15,
    color: COLORS.darkGrey,
    backgroundColor: COLORS.backgroundLight,
  },
  modalButtonContainer: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalButtonPrimary: {
    backgroundColor: COLORS.purple,
  },
  modalButtonSecondary: {
    backgroundColor: COLORS.backgroundLight,
    borderWidth: 1,
    borderColor: COLORS.lightGrey,
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
  modalButtonTextPrimary: {
    color: COLORS.white,
  },
  modalButtonTextSecondary: {
    color: COLORS.darkGrey,
  },
  ingredientSearchContainer: {
    borderWidth: 1,
    borderColor: COLORS.lightGrey,
    borderRadius: 12,
    maxHeight: 200,
    backgroundColor: COLORS.white,
  },
  ingredientSearchItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.lightGrey,
  },
  ingredientSearchItemLast: {
    borderBottomWidth: 0,
  },
  ingredientSearchImage: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: COLORS.backgroundLight,
  },
  ingredientSearchInfo: {
    flex: 1,
  },
  ingredientSearchName: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.darkGrey,
  },
  ingredientSearchPrice: {
    fontSize: 12,
    color: COLORS.grey,
    marginTop: 2,
  },
  selectedIngredientCard: {
    marginTop: 12,
    padding: 12,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.purple,
  },
  selectedIngredientInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  selectedIngredientImage: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: COLORS.backgroundLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedIngredientName: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.darkGrey,
  },
  selectedIngredientPrice: {
    fontSize: 13,
    color: COLORS.grey,
    marginTop: 2,
  },
  priceDisplayContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    backgroundColor: '#F3E5F5',
    borderRadius: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: '#E1BEE7',
  },
  priceDisplayText: {
    fontSize: 14,
    color: COLORS.darkGrey,
    fontWeight: '500',
    flex: 1,
  },
  priceDisplayAmount: {
    fontSize: 18,
    fontWeight: '700',
    color: '#7B1FA2',
  },
  priceDisplayNote: {
    fontSize: 11,
    color: '#9C27B0',
    marginTop: 2,
    fontWeight: '500',
  },
  helperText: {
    fontSize: 12,
    color: COLORS.grey,
    marginTop: 4,
    fontStyle: 'italic',
  },
  assignMemberContainer: {
    gap: 8,
  },
  assignMemberLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.darkGrey,
    marginBottom: 4,
  },
  memberSelectButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.lightGrey,
  },
  memberSelectText: {
    fontSize: 15,
    color: COLORS.darkGrey,
  },
  memberSelectPlaceholder: {
    fontSize: 15,
    color: COLORS.grey,
  },
  memberDropdown: {
    maxHeight: 200,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.lightGrey,
    marginTop: 4,
  },
  memberDropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.lightGrey,
  },
  memberDropdownItemLast: {
    borderBottomWidth: 0,
  },
  memberDropdownAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.purple,
    justifyContent: 'center',
    alignItems: 'center',
  },
  memberDropdownAvatarText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.white,
  },
  memberDropdownInfo: {
    flex: 1,
  },
  memberDropdownName: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.darkGrey,
  },
  memberDropdownEmail: {
    fontSize: 12,
    color: COLORS.grey,
    marginTop: 2,
  },
  selectedMemberCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.purple,
    gap: 10,
  },
  selectedMemberAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.purple,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedMemberAvatarText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.white,
  },
  selectedMemberInfo: {
    flex: 1,
  },
  selectedMemberName: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.darkGrey,
  },
  emptyShoppingText: {
    fontSize: 14,
    color: COLORS.grey,
    textAlign: 'center',
    marginTop: 8,
  },
  ownerInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
  },
  ownerAvatar: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: COLORS.purple,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ownerAvatarImage: {
    width: 20,
    height: 20,
    borderRadius: 10,
  },
  ownerName: {
    fontSize: 12,
    color: COLORS.grey,
  },
  // ============ CHAT STYLES ============
  chatContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  chatMessagesList: {
    flex: 1,
    paddingHorizontal: 16,
  },
  chatMessagesContent: {
    paddingVertical: 16,
    gap: 12,
  },
  chatMessageCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 14,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  chatMessageCardOwn: {
    backgroundColor: '#DCF8C6',
    marginLeft: 60,
    alignSelf: 'flex-end',
    borderBottomRightRadius: 4,
  },
  chatMessageCardOther: {
    marginRight: 60,
    alignSelf: 'flex-start',
    borderBottomLeftRadius: 4,
  },
  chatMessageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  chatMessageAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
  },
  chatMessageAvatarImage: {
    width: '100%',
    height: '100%',
  },
  chatMessageAvatarPlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  chatMessageAvatarPlaceholderOwner: {
    backgroundColor: '#1976D2',
  },
  chatMessageAvatarPlaceholderManager: {
    backgroundColor: '#F57C00',
  },
  chatMessageAvatarPlaceholderMember: {
    backgroundColor: '#7B1FA2',
  },
  chatMessageAvatarText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.white,
  },
  chatMessageHeaderInfo: {
    // flex: 1, // Removed to allow container to size to name width
    gap: 2,
    marginRight: 8, // Add some spacing just in case
  },
  chatMessageSenderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  chatMessageSenderName: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.darkGrey,
  },
  chatMessageRoleBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  chatMessageRoleBadgeOwner: {
    backgroundColor: '#E3F2FD',
  },
  chatMessageRoleBadgeManager: {
    backgroundColor: '#FFF3E0',
  },
  chatMessageRoleBadgeMember: {
    backgroundColor: '#E8F5E9',
  },
  chatMessageRoleText: {
    fontSize: 10,
    fontWeight: '600',
  },
  chatMessageRoleTextOwner: {
    color: '#1976D2',
  },
  chatMessageRoleTextManager: {
    color: '#F57C00',
  },
  chatMessageRoleTextMember: {
    color: '#2E7D32',
  },
  chatMessageTime: {
    fontSize: 11,
    color: COLORS.grey,
  },
  chatMessageTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.purple,
    marginBottom: 4,
  },
  chatMessageContent: {
    fontSize: 14,
    color: COLORS.darkGrey,
    lineHeight: 20,
  },
  chatInputContainer: {
    paddingTop: 12,
    paddingBottom: 0,
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: COLORS.lightGrey,
  },
  chatInputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  chatInputWrapper: {
    flex: 1,
    backgroundColor: COLORS.backgroundLight,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 8,
    minHeight: 44,
    maxHeight: 120,
  },
  chatInput: {
    fontSize: 15,
    color: COLORS.darkGrey,
    paddingVertical: 0,
    maxHeight: 100,
  },
  chatSendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.purple,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.purple,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  chatSendButtonDisabled: {
    backgroundColor: COLORS.grey,
    shadowOpacity: 0,
    elevation: 0,
  },
  chatImageButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    borderWidth: 1,
    borderColor: COLORS.lightGrey,
  },
  chatImageButtonDisabled: {
    opacity: 0.5,
  },
  chatImagePreview: {
    position: 'relative',
    marginBottom: 8,
    marginHorizontal: 16,
    borderRadius: 12,
    overflow: 'hidden',
    width: 200,
    height: 150,
  },
  chatImagePreviewImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  chatImagePreviewRemove: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 12,
    padding: 2,
  },
  chatMessageImageContainer: {
    marginBottom: 8,
    borderRadius: 12,
    overflow: 'hidden',
    maxWidth: 250,
  },
  chatMessageImage: {
    width: 250,
    height: 200,
    resizeMode: 'cover',
  },
  chatEmptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
    paddingVertical: 60,
    gap: 16,
  },
  chatEmptyIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#EDE7F6',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  chatEmptyTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.darkGrey,
    textAlign: 'center',
  },
  chatEmptySubtitle: {
    fontSize: 14,
    color: COLORS.grey,
    textAlign: 'center',
    lineHeight: 20,
  },
  chatLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
    gap: 12,
  },
  chatLoadingText: {
    fontSize: 14,
    color: COLORS.grey,
  },
  // Typing Indicator Styles
  typingIndicatorContainer: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: COLORS.lightGrey,
  },
  typingIndicatorContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  typingIndicatorAvatars: {
    flexDirection: 'row',
    gap: -8, // Overlap avatars slightly
  },
  typingAvatarContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: COLORS.white,
    overflow: 'hidden',
    backgroundColor: COLORS.white,
  },
  typingAvatar: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  typingAvatarPlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  typingAvatarPlaceholderOwner: {
    backgroundColor: COLORS.orange,
  },
  typingAvatarPlaceholderManager: {
    backgroundColor: COLORS.blue,
  },
  typingAvatarPlaceholderMember: {
    backgroundColor: COLORS.lightBlue,
  },
  typingAvatarText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.white,
  },
  typingIndicatorTextContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  typingIndicatorText: {
    fontSize: 13,
    color: COLORS.grey,
    fontStyle: 'italic',
  },
  typingDots: {
    flexDirection: 'row',
    gap: 4,
    alignItems: 'center',
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.primary,
  },
});
